print("atharva lal shrestha")
a="deerwalk sifal school"
print(a[9:15])
print(a[5])
print(a*5)
print(a[0:21:2])
print(a[0:8:2])
print(a[0:21:3])
print(a[0:15:2])
b='deerwalk institute of technology'
x = len(b)
print (x)
print( 'a' in b)
print(b.replace('d','D'))
print(len(a))
print(a.upper())
print(b.title())
print(a.capitalize())
print(a[::2])
c = 'nepal aviation institute'
print(c[0:6])
print(c[:6])
print(c[6:15])
print(c[15:24])
print(c[15:])
print(c[::3])
print(len(c))
print('i' in c)