a = "nepal institute of agriculture"
print(len(a))
print(a.title())
print('nepal' in a)
print(a[:31])
print(a[6:15])
print(a[:31:2])
print(int(1.1))
print(int(1.9))
print(int(True))
print(int(False))
print(int("2"))
print(type(int("2")))
print(int('1')+int('2'))
print(float(1))
print(float("1"))
print(float('1.1')+float('1.9'))
print(float(True))
print(str(1)+str(1))
print(str(True)+str(True))
print(str(1.1)+str(1.9))
print(bool(0))
print(bool(1))
print(bool(0.000000001))
print(bool(2))
print(bool('ab'))
print(bool(''))
a = input("enter first number = ")
b = input('enter second number =')
c = input('enter third number = ')
print (int(a) + int(b) + int(c))
print ( int(a)* int(b) * int(c))
print ( int(a)/int(b)/int(c))
print ( int(a)-int(b)-int(c))
x = int(input('enter a number'))
if (x%2)==0:print("x is even")
else:
    print("the number is odd")
a = int(input('enter a number'))
print(a * a)
# take two number and 1 number is raised to the power of 2 number


