
name = (input("enter college name"))
if(name == "deerwalk"):print("student of deerwalk")
else : print("not a student of deerwalk")
print(name[0:9:])
section = (input("enter section name"))
print ( section[0:6:2])
print(name.capitalize())
print(section.upper())
print(section.replace("changla","khumbutshe"))
