a=('sun','mon','tue','wed','thurs','fri','sat')
print(a)
print(type(a))
print(a[0])
print(a[-1])
print(a[::2])
print(len(a))
print('sun' in a)
print('Sun' in a)
print(a[::])
i,j,k = (1,2,3)
print(i)
print(j)
print(k)
print(a[2])
